Col name visit_start_time & concept map update
following error received:

ERROR: column "visit_start_time" does not exist LINE 26: date_part('hour',visit_start_time)||':'||date_part('minu...
HINT: Perhaps you meant to reference the column "v.visit_start_date". Query returned successfully in 203 sec.

The column name in the visit_start_time not present in stlouis_pcornet the column visit_start_datetime. Following modification were made in script:
1.  the reference column from visit_occurrence in the query was changed from
      visit_start_time                 to                visit_start_datetime
2. The reference to concept map was changed
      cz_omop_pedsnet_pcornet_map                   to                   pedsnet_pcornet_valueset_map