Update Lab_Result_CM_ETL.sql
To  resolve the following error while running ETL:
ERROR:  numeric field overflow
DETAIL:  A field with precision 20, scale 8 must round to an absolute value less than 10^12.

The result_num filed datatype length changed from 20 to 25