drug_exposure_start_time doesn't exist
modified code, following things were changed
`drug_exposure_start_time`  to `drug_exposure_start_datetime`
and
`cz_omop_pcornet_concept_map`    to  `pedsnet_pcornet_valueset_map`

```
ERROR:  column "drug_exposure_start_time" does not exist
LINE 23:  date_part('hour',drug_exposure_start_time)||':'||date_part(...
                           ^
HINT:  Perhaps you meant to reference the column "de.drug_exposure_start_date".
```